name: build
permissions:
  contents: read

on:
  push:
    branches:
      - 'DEV-**'
      - main
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Verify that the Docker image for the action builds
        run: docker build . --file Dockerfile

      - name: Do qbee login
        uses: qbee-io/authenticate-action@main
        with:
          login: ${{ secrets.QBEE_USER }}
          password: ${{ secrets.QBEE_PASSWORD }}
          
      - name: test file upload old format
        uses: ./
        with:
          filename: README.md
          local_directory: .
          qbee_directory: /qbee-github-actions/upload

      - name: test file upload new format
        uses: ./
        with:
          source: README.md
          destination: /qbee-github-actions/upload
      
      - name: create test data
        run: |
          mkdir -p testdata/subdir
          echo "$RANDOM" > testdata/test.txt
          echo "$RANDOM" > testdata/test2.txt
          echo "$RANDOM" > testdata/subdir/test.txt
          echo "$RANDOM" > testdata/subdir/test3.txt

      - name: test sync
        uses: ./
        with:
          source: testdata
          destination: /qbee-github-actions/sync
          action: sync
          
      - name: test sync with include
        uses: ./
        with:
          source: testdata
          destination: /qbee-github-actions/sync
          action: sync
          exclude: test2.txt,subdir
          include: subdir/test.txt,subdir/test3.txt